[project]
name = 'circular-economy-marketplace'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.product-lifecycle-extender]
path = 'contracts/product-lifecycle-extender.clar'
clarity_version = 2
epoch = 2.5

[contracts.waste-resource-converter]
path = 'contracts/waste-resource-converter.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
